repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v3.4.0"
    hooks:
      - id: check-merge-conflict
        stages: [ commit, push ]

  - repo: local
    hooks:

      - id: black
        name: black
        entry: poetry run black src
        language: system
        types: [ python ]
        stages: [ commit ]

      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [ python ]
        stages: [ commit ]

      - id: mypy
        name: mypy
        entry: poetry run mypy src
        language: system
        pass_filenames: false
        stages: [ commit ]

      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [ python ]
        stages: [ push ]

      - id: pyright
        name: pyright
        entry: poetry run pyright src
        language: system
        pass_filenames: false
        stages: [ push ]
