name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.10"

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Cache .mypy_cache
        id: cache-mypy
        uses: actions/cache@v3
        with:
          key: ${{ matrix.python-version }}-${{ runner.os }}
          path: .mypy_cache

      - uses: actions/setup-python@v4.1.0
        id: python-setup
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install dependencies
        if: steps.python-setup.outputs.cache-hit != 'true'
        run: poetry install --with dev

      - name: Run flakeheaven
        run: poetry run flakeheaven lint

      - name: Run mypy
        run: poetry run mypy vkbottle

      - name: Run tests
        run: poetry run pytest
