name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry

    - name: Set up Python 3.10
      uses: actions/setup-python@v4.1.0
      with:
        python-version: "3.10"
        cache: poetry

    - name: Install dependencies
      if: steps.python-setup.outputs.cache-hit != 'true'
      run: poetry install --with dev

    - name: Run flake8
      run: |
        poetry run flake8

    - name: Run mypy
      run: |
        poetry run mypy src
